packages:
  - 'backend/*'
  - 'frontend/*'
  - 'data/*'
  - 'graphql/*'
  - 'lang/*'
  - 'model/*'
  - 'model/string/*'
  - 'model/reference/*'
  - 'model/attachment/*'
  - 'scripts/*'
  - 'sql/*'
  - 'ui/*'
