name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache sharp dependencies
        uses: actions/cache@v2
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Install sharp dependencies
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: CYPRESS_CACHE_FOLDER=./tmp/Cypress pnpm install --frozen-lockfile

      - name: Versions
        run: npx turbo --version

      - name: Build
        run: |
          npx turbo build

      - name: Test
        run: npx turbo test

      - name: Model editor cypress tests
        run: cd model/editor && CYPRESS_CACHE_FOLDER=./tmp/Cypress ./scripts/run-cypress.sh
